# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments: false

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
github_url: https://github.com/ShikiEiki
email_url: 515073770@qq.com
rss_url: \#

# Footer About Text
footer_about: "欢迎访问我的博客,本博客使用github page和Hexo搭建,技术小白自我进化中,很乐意讨论技术问题,欢迎给我发邮件~~"

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

